# Generated by Django 4.2.1 on 2023-09-28 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=50)),
                ('fees', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('roll', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('OTHER', 'other')], default='MALE', max_length=8)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('date_enrolled', models.DateTimeField(auto_now_add=True)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled', to='api.courses')),
            ],
        ),
    ]
